// localStorage.clear()
const employees = [
  {
    id: 1,
    firstName: "Amit",
    email: "am@am.com",
    pwd: "123",
    totalTasks: 3,
    activeTasks: 1,
    completedTasks: 1,
    failedTasks: 1,
    newTasks: 0,
    tasks: [
      {
        taskTitle: "Fix login bug",
        description: "Fix incorrect credential rejection on login",
        taskDate: "2025-05-01",
        category: "Bug Fix",
        active: true,
        failed: false,
        newTask: false,
        completed: false,
      },
      {
        taskTitle: "Refactor dashboard layout",
        description: "Improve spacing and colors",
        taskDate: "2025-05-05",
        category: "UI",
        active: false,
        failed: false,
        newTask: false,
        completed: true,
      },
      {
        taskTitle: "Add unit tests for UserService",
        description: "Cover all core methods with JUnit",
        taskDate: "2025-05-09",
        category: "Testing",
        active: false,
        failed: true,
        newTask: false,
        completed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Ravi",
    email: "employee2@example.com",
    pwd: "123",
    totalTasks: 4,
    activeTasks: 1,
    completedTasks: 1,
    failedTasks: 1,
    newTasks: 1,
    tasks: [
      {
        taskTitle: "Improve query performance",
        description: "Analyze slow queries and add indexes",
        taskDate: "2025-05-07",
        category: "Database",
        active: true,
        failed: false,
        newTask: false,
        completed: false,
      },
      {
        taskTitle: "Implement data export to Excel",
        description: "Allow users to export reports",
        taskDate: "2025-05-11",
        category: "Feature",
        active: false,
        failed: false,
        newTask: true,
        completed: false,
      },
      {
        taskTitle: "Prepare report for client presentation",
        description: "Summarize Q2 deliverables",
        taskDate: "2025-05-03",
        category: "Management",
        active: false,
        failed: false,
        newTask: false,
        completed: true,
      },
      {
        taskTitle: "Investigate email not sent",
        description: "Check SMTP logs and debug handler",
        taskDate: "2025-05-02",
        category: "Bug Fix",
        active: false,
        failed: true,
        newTask: false,
        completed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Neha",
    email: "employee3@example.com",
    pwd: "123",
    totalTasks: 3,
    activeTasks: 1,
    completedTasks: 1,
    failedTasks: 0,
    newTasks: 1,
    tasks: [
      {
        taskTitle: "Write Swagger docs for REST APIs",
        description: "Document endpoints and parameters",
        taskDate: "2025-05-04",
        category: "Documentation",
        active: false,
        failed: false,
        newTask: false,
        completed: true,
      },
      {
        taskTitle: "Cleanup Spring Security config",
        description: "Split into multiple config classes",
        taskDate: "2025-05-10",
        category: "Code Refactor",
        active: true,
        failed: false,
        newTask: false,
        completed: false,
      },
      {
        taskTitle: "Generate test data for QA",
        description: "Seed DB with realistic user data",
        taskDate: "2025-05-12",
        category: "Testing",
        active: false,
        failed: false,
        newTask: true,
        completed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Priya",
    email: "employee4@example.com",
    pwd: "123",
    totalTasks: 4,
    activeTasks: 1,
    completedTasks: 2,
    failedTasks: 0,
    newTasks: 1,
    tasks: [
      {
        taskTitle: "Fix calculation mismatch in invoice",
        description: "Total doesn't match item sums",
        taskDate: "2025-05-06",
        category: "Bug Fix",
        active: true,
        failed: false,
        newTask: false,
        completed: false,
      },
      {
        taskTitle: "Add pagination to users list",
        description: "Limit 10 users per page",
        taskDate: "2025-05-08",
        category: "Feature",
        active: false,
        failed: false,
        newTask: true,
        completed: false,
      },
      {
        taskTitle: "Review teammate PRs",
        description: "Give feedback and merge",
        taskDate: "2025-05-10",
        category: "Collaboration",
        active: false,
        failed: false,
        newTask: false,
        completed: true,
      },
      {
        taskTitle: "Setup Sentry for backend",
        description: "Track and log unhandled exceptions",
        taskDate: "2025-05-09",
        category: "DevOps",
        active: false,
        failed: false,
        newTask: false,
        completed: true,
      },
    ],
  },
  {
    id: 5,
    firstName: "Karan",
    email: "employee5@example.com",
    pwd: "123",
    totalTasks: 3,
    activeTasks: 1,
    completedTasks: 1,
    failedTasks: 1,
    newTasks: 0,
    tasks: [
      {
        taskTitle: "Push latest build to staging",
        description: "Verify new features before production",
        taskDate: "2025-05-03",
        category: "Deployment",
        active: false,
        failed: false,
        newTask: false,
        completed: true,
      },
      {
        taskTitle: "Internal write-up on best practices",
        description: "Summarize error handling strategies",
        taskDate: "2025-05-04",
        category: "Knowledge Sharing",
        active: false,
        failed: true,
        newTask: false,
        completed: false,
      },
      {
        taskTitle: "Run OWASP ZAP scan",
        description: "Check for known vulnerabilities",
        taskDate: "2025-05-06",
        category: "Security",
        active: true,
        failed: false,
        newTask: false,
        completed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    firstName:"Admin",
    email: "admin@example.com",
    pwd: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem('employees'))
  const admin = JSON.parse(localStorage.getItem('admin'))
  return { employees, admin };
};

